import { DEFAULT_GRID, cellKey, inBounds, cellToWorldCenter, worldToCell } from './grid.js';
import { getPlacementCells, normalizeRotation } from './footprint.js';
import { validatePath } from './path-state.js';
import { getPreset } from './presets.js';
const clone = (v) => v == null ? v : JSON.parse(JSON.stringify(v));
const result = (valid, extra = {}) => ({ valid, changed: valid, ...extra });
export function createWorldState(options = {}) {
  const grid = { ...DEFAULT_GRID, ...clone(options.grid || {}), origin: { ...DEFAULT_GRID.origin, ...(options.grid?.origin || {}) } };
  const state = { schema:'mossbound-world', version:1, world:{ presetId:options.presetId || 'blank', seed:options.seed || 4207, grid }, placements:new Map(), occupancy:new Map(), terrain:new Map(), paths:new Map(), history:[], redo:[] };
  const derive = (p) => getPlacementCells(p.anchor, p.footprint, p.rotation);
  const validatePlacement = (p, ignoreId = null) => { const cells=derive(p); for (const c of cells) { if (!inBounds(grid,c)) return result(false,{reason:'bounds',cell:c,cells}); const occupant=state.occupancy.get(c.key); if (occupant && occupant!==ignoreId) return result(false,{reason:'occupied',cell:c,occupantId:occupant,cells}); } return result(true,{cells}); };
  const apply = (mutation, inverse, meta) => { const before = api.toJSON(); const r=mutation(); if (!r?.valid) return r; state.history.push({ before, after:api.toJSON(), meta }); state.redo.length=0; return {...r, commandId:state.history.length}; };
  const api = {
    grid, state,
    boardToWorld: (cell) => cellToWorldCenter(grid,cell), worldToCell: (world) => worldToCell(grid,world),
    getPlacement: (id) => state.placements.get(id), getPlacements: () => [...state.placements.values()], getTerrain: () => [...state.terrain.values()], getPath: (id) => state.paths.get(id), getPaths: () => [...state.paths.values()],
    addPlacement(spec, options = {}) { const p={ id:spec.id || `object-${Date.now()}-${Math.random().toString(36).slice(2,6)}`, kind:spec.kind, anchor:{...spec.anchor}, footprint:clone(spec.footprint || [1,1]), rotation:normalizeRotation(spec.rotation), data:clone(spec.data || {}) }; const check=validatePlacement(p); if(!check.valid) return check; const mutation=()=>{ state.placements.set(p.id,p); check.cells.forEach(c=>state.occupancy.set(c.key,p.id)); return result(true,{object:clone(p),cells:check.cells}); }; return options.history===false ? mutation() : apply(mutation,null,{type:'placement.add',id:p.id}); },
    removePlacement(id, options = {}) { const p=state.placements.get(id); if(!p) return result(false,{reason:'missing'}); const mutation=()=>{ derive(p).forEach(c=>{if(state.occupancy.get(c.key)===id)state.occupancy.delete(c.key)}); state.placements.delete(id); return result(true,{object:clone(p)}); }; return options.history===false ? mutation() : apply(mutation,null,{type:'placement.remove',id}); },
    transformPlacement(id, patch, options = {}) { const old=state.placements.get(id); if(!old) return result(false,{reason:'missing'}); const next={...clone(old),...clone(patch),anchor:{...(patch.anchor||old.anchor)},rotation:normalizeRotation(patch.rotation ?? old.rotation)}; const check=validatePlacement(next,id); if(!check.valid)return check; const mutation=()=>{derive(old).forEach(c=>{if(state.occupancy.get(c.key)===id)state.occupancy.delete(c.key)});state.placements.set(id,next);check.cells.forEach(c=>state.occupancy.set(c.key,id));return result(true,{object:clone(next),cells:check.cells});}; return options.history===false ? mutation() : apply(mutation,null,{type:'placement.transform',id}); },
    movePlacement(id,anchor,options={}) { return api.transformPlacement(id,{anchor},options); }, rotatePlacement(id,rotation,options={}) { return api.transformPlacement(id,{rotation},options); },
    paintTerrain(cell, patch, options={}) { if(!inBounds(grid,cell))return result(false,{reason:'bounds'}); const key=cellKey(cell), old=state.terrain.get(key), next={x:cell.x,z:cell.z,...clone(old||{}),...clone(patch)}; const mutation=()=>{state.terrain.set(key,next);return result(true,{cell,value:clone(next)})};return options.history===false?mutation():apply(mutation,null,{type:'terrain.paint',key}); },
    addPath(spec, options={}) { const p={...clone(spec),id:spec.id||`path-${Date.now()}`};const check=validatePath(p,grid);if(!check.valid)return check;const mutation=()=>{state.paths.set(p.id,p);return result(true,{path:clone(p),masks:[...check.masks]})};return options.history===false?mutation():apply(mutation,null,{type:'path.add',id:p.id}); },
    removePath(id,options={}) { if(!state.paths.has(id))return result(false,{reason:'missing'});const mutation=()=>{const path=state.paths.get(id);state.paths.delete(id);return result(true,{path:clone(path)})};return options.history===false?mutation():apply(mutation,null,{type:'path.remove',id}); },
    applyPreset(id) { const preset=getPreset(id); const mutation=()=>{state.world.presetId=preset.id;state.world.seed=preset.seed;state.placements.clear();state.occupancy.clear();state.terrain.clear();state.paths.clear();return result(true,{preset:clone(preset)})};return apply(mutation,null,{type:'world.preset',id}); },
    undo(){const cmd=state.history.pop();if(!cmd)return false;state.redo.push(api.toJSON());api.load(cmd.before,{history:false});return true;}, redo(){const snap=state.redo.pop();if(!snap)return false;state.history.push({before:api.toJSON(),after:snap});api.load(snap,{history:false});return true;},
    assertInvariants(){for(const [id,p] of state.placements)for(const c of derive(p))if(state.occupancy.get(c.key)!==id)throw Error(`occupancy mismatch ${id}`);for(const [key,id] of state.occupancy)if(!state.placements.has(id))throw Error(`orphan occupancy ${key}`);return true;},
    toJSON(){return {schema:state.schema,version:state.version,world:clone(state.world),placements:[...state.placements.values()].map(clone),terrain:[...state.terrain.values()].map(clone),paths:[...state.paths.values()].map(clone)};},
    load(snapshot){state.world=clone(snapshot.world||state.world);state.placements.clear();state.occupancy.clear();state.terrain.clear();state.paths.clear();for(const p of snapshot.placements||[]){const r=api.addPlacement(p,{history:false});if(!r.valid)throw Error(`invalid placement ${r.reason}`)}for(const t of snapshot.terrain||[])state.terrain.set(cellKey(t),clone(t));for(const p of snapshot.paths||[]){const r=api.addPath(p,{history:false});if(!r.valid)throw Error(`invalid path ${r.reason}`)}return api;}
  }; return api;
}
